ACCEPT_KEYWORDS = [
    "accept",
    "accept all",
    "accept all cookies",
    "accept cookies",
    "allow",
    "allow all",
    "allow all cookies",
    "allow cookies",
    "agree",
    "agree all",
    "agree to all",
    "i agree",
    "i accept",
    "yes",
    "yes, i agree",
    "ok",
    "okay",
    "got it",
    "sounds good",
    "continue",
    "continue to site",
    "continue browsing",
    "continue with all",
    "enable all",
    "enable cookies",
    "enable all cookies",
    "consent",
    "give consent",
    "accept & continue",
    "agree & continue",
    "accept and close",
    "accept and proceed",
    "confirm",
    "confirm all",
    "understand",
    "i understand",
]

REJECT_KEYWORDS = [
    "decline",
    "decline all",
    "decline cookies",
    "reject",
    "reject all",
    "reject cookies",
    "deny",
    "deny all",
    "disagree",
    "refuse",
    "opt out",
    "opt-out",
    "do not accept",
    "do not agree",
    "do not allow",
    "disable",
    "disable all",
    "disable cookies",
    "only necessary",
    "use necessary cookies only",
    "essential only",
    "strictly necessary only",
    "save without consent",
]

CUSTOMIZE_KEYWORDS = [
    "cookie settings",
    "privacy settings",
    "manage",
    "manage cookies",
    "manage preferences",
    "manage options",
    "preferences",
    "customize",
    "customise",
    "cookie preferences",
    "privacy preferences",
    "settings",
    "advanced settings",
    "more options",
    "show purposes",
    "edit preferences",
    "save choices",
    "confirm choices",
    "save settings",
    "save preferences",
    "close",
    "dismiss",
    "no thanks",
    "not now",
    "later",
    "skip",
]

ACTION_KEYWORDS = ACCEPT_KEYWORDS + REJECT_KEYWORDS + CUSTOMIZE_KEYWORDS
